#pragma once

static const char *HTML_PAGE = 
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Smart Crib</title>"
"<style>"
"body{font-family:'Segoe UI',sans-serif;background:#eef2f3;margin:0;padding:10px;color:#333;text-align:center}"
".card{background:#fff;max-width:500px;margin:auto;border-radius:15px;box-shadow:0 4px 10px rgba(0,0,0,0.1);padding:15px;margin-bottom:15px}"
"h1{margin:0 0 10px;font-size:1.4rem;color:#444}.time{font-size:2rem;font-weight:700;color:#2c3e50;margin:5px 0}"
".grid{display:flex;justify-content:space-around;margin:15px 0}"
".box{background:#f8f9fa;padding:10px;border-radius:8px;width:42%}.val{font-size:1.5rem;font-weight:700;color:#007bff}"
"button{width:32%;padding:10px;border:none;border-radius:6px;font-weight:700;cursor:pointer;color:#fff;margin-bottom:10px}"
".btn-0{background:#3498db}.btn-1{background:#2ecc71}.btn-2{background:#9b59b6}"
".active{box-shadow:inset 0 0 0 3px rgba(0,0,0,0.3);transform:scale(0.98)}"
".sched-item{border:1px solid #ddd;border-radius:8px;padding:10px;margin-bottom:10px;text-align:left;background:#fff}"
".sched-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;font-weight:bold}"
".sched-row{display:flex;justify-content:space-between;gap:5px;margin-bottom:5px}"
"input[type=number]{width:45px;padding:5px;border:1px solid #ccc;border-radius:4px;text-align:center}"
"input[type=checkbox]{transform:scale(1.5)}"
".save-btn{width:100%;background:#f39c12;margin-top:5px;color:white;border:none;padding:8px;cursor:pointer;border-radius:4px}"
"</style></head><body>"

"<div class='card'>"
" <h1>👶 Cuna Inteligente</h1>"
" <div class='time' id='time'>--:--:--</div>"
" <div class='grid'>"
"  <div class='box'><div class='val' id='temp'>--</div><small>TEMP (°C)</small></div>"
"  <div class='box'><div class='val' id='pwm'>--</div><small>FAN (%)</small></div>"
" </div>"
" <div style='margin-bottom:15px'>PIR: <b id='pir'>--</b> | MODO: <b id='mode'>--</b></div>"
" <div>"
"  <button class='btn-0' id='b0' onclick='setMode(0)'>MANUAL</button>"
"  <button class='btn-1' id='b1' onclick='setMode(1)'>AUTO</button>"
"  <button class='btn-2' id='b2' onclick='setMode(2)'>PROG</button>"
" </div>"
" <div id='manual-ctrl' style='display:none;margin-top:10px'>"
"  <label>Velocidad Manual:</label><br>"
"  <input type='range' id='slider' min='0' max='100' style='width:100%' onchange='setSpeed(this.value)'>"
" </div>"
"</div>"

"<div class='card' id='sched-ctrl' style='display:none'>"
" <h3>📅 Configuración de Horarios</h3>"
" <div id='sched-list'>Cargando horarios...</div>"
"</div>"

"<script>"
"let scheduleData=[];"
"function update(){"
" fetch('/api/status').then(r=>r.json()).then(d=>{"
"   document.getElementById('time').innerText=d.time;"
"   document.getElementById('temp').innerText=d.temp.toFixed(1);"
"   document.getElementById('pwm').innerText=d.pwm;"
"   document.getElementById('pir').innerText=d.pir?'DETECTADO':'---';"
"   document.getElementById('mode').innerText=['MAN','AUTO','PROG'][d.mode];"
"   for(let i=0;i<3;i++)document.getElementById('b'+i).classList.remove('active');"
"   document.getElementById('b'+d.mode).classList.add('active');"
"   document.getElementById('manual-ctrl').style.display=(d.mode==0)?'block':'none';"
"   document.getElementById('sched-ctrl').style.display=(d.mode==2)?'block':'none';"
"   if(d.mode==0 && document.getElementById('slider').value!=d.manual_duty){"
"     document.getElementById('slider').value = d.manual_duty;"
"   }"
"   if(d.schedules && JSON.stringify(d.schedules)!==JSON.stringify(scheduleData)){"
"     scheduleData=d.schedules; renderSchedules();"
"   }"
" }).catch(e=>console.log('Error:',e));"
"}"

"function renderSchedules(){"
" let h=''; scheduleData.forEach((s,i)=>{"
"  h+=`<div class='sched-item'>`+"
"  `<div class='sched-head'><span>Registro #${i+1}</span> <input type='checkbox' id='act${i}' ${s.act?'checked':''}></div>`+"
"  `<div class='sched-row'>`+"
"   `<span>Hora: <input type='number' id='sh${i}' value='${s.sh}'>:<input type='number' id='sm${i}' value='${s.sm}'></span>`+"
"   `<span>a <input type='number' id='eh${i}' value='${s.eh}'>:<input type='number' id='em${i}' value='${s.em}'></span>`+"
"  `</div>`+"
"  `<div class='sched-row'>`+"
"   `<span>Temp: <input type='number' id='tmin${i}' value='${s.tmin}'> °C</span>`+"
"   `<span>a <input type='number' id='tmax${i}' value='${s.tmax}'> °C</span>`+"
"  `</div>`+"
"  `<button class='save-btn' onclick='saveSched(${i})'>Guardar R#${i+1}</button>`+"
"  `</div>`;"
" });"
" document.getElementById('sched-list').innerHTML=h;"
"}"

"function setMode(m){fetch('/api/settings',{method:'POST',body:JSON.stringify({mode:m})}).then(update)}"
"function setSpeed(v){fetch('/api/settings',{method:'POST',body:JSON.stringify({mode:0,manual_duty:parseInt(v)})}).then(update)}"

"function saveSched(i){"
" let body={"
"  sched_idx:i,"
"  act:document.getElementById('act'+i).checked,"
"  sh:parseInt(document.getElementById('sh'+i).value),"
"  sm:parseInt(document.getElementById('sm'+i).value),"
"  eh:parseInt(document.getElementById('eh'+i).value),"
"  em:parseInt(document.getElementById('em'+i).value),"
"  tmin:parseFloat(document.getElementById('tmin'+i).value),"
"  tmax:parseFloat(document.getElementById('tmax'+i).value)"
" };"
" fetch('/api/settings',{method:'POST',body:JSON.stringify(body)}).then(update);"
"}"

"setInterval(update,1000);update();"
"</script></body></html>";